In [1]:
import gensim
from gensim.models import Word2Vec, KeyedVectors

In [2]:
import gensim.downloader as api

wv = api.load('word2vec-google-news-300')

vec_king = wv['king']

In [3]:
vec_king.shape

(300,)

In [4]:
import pandas as pd
messages = pd.read_csv(r'D:\Machine learning\ML Programs\NLP\SpamClassifier\smsspamcollection\SMSSpamCollection.csv', sep='\t',names=['label','message'])
messages

     label                                            message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham               Will ü b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [5]:
from nltk.stem import WordNetLemmatizer
lemmatizer = WordNetLemmatizer()

In [6]:
import re
corpus = []
for i in range(0, len(messages)):
    review = re.sub('[^a-zA-Z]', ' ', messages['message'][i])
    review = review.lower()
    review = review.split()
    
    review = [lemmatizer.lemmatize(word) for word in review]
    review = ' '.join(review)
    corpus.append(review)

In [7]:
[[i,j,k] for i,j,k in zip(list(map(len,corpus)),corpus, messages['message']) if i<1]

[[0, '', '645'], [0, '', ':) '], [0, '', ':-) :-)']]

In [8]:
corpus

['go until jurong point crazy available only in bugis n great world la e buffet cine there got amore wat',
 'ok lar joking wif u oni',
 'free entry in a wkly comp to win fa cup final tkts st may text fa to to receive entry question std txt rate t c s apply over s',
 'u dun say so early hor u c already then say',
 'nah i don t think he go to usf he life around here though',
 'freemsg hey there darling it s been week s now and no word back i d like some fun you up for it still tb ok xxx std chgs to send to rcv',
 'even my brother is not like to speak with me they treat me like aid patent',
 'a per your request melle melle oru minnaminunginte nurungu vettam ha been set a your callertune for all caller press to copy your friend callertune',
 'winner a a valued network customer you have been selected to receivea prize reward to claim call claim code kl valid hour only',
 'had your mobile month or more u r entitled to update to the latest colour mobile with camera for free call the mobile update co free on',
 'i m gonna be home soon and i don t want to talk about this stuff anymore tonight k i ve cried enough today',
 'six chance to win cash from to pound txt csh and send to cost p day day tsandcs apply reply hl info',
 'urgent you have won a week free membership in our prize jackpot txt the word claim to no t c www dbuk net lccltd pobox ldnw a rw',
 'i ve been searching for the right word to thank you for this breather i promise i wont take your help for granted and will fulfil my promise you have been wonderful and a blessing at all time',
 'i have a date on sunday with will',
 'xxxmobilemovieclub to use your credit click the wap link in the next txt message or click here http wap xxxmobilemovieclub com n qjkgighjjgcbl',
 'oh k i m watching here',
 'eh u remember how spell his name yes i did he v naughty make until i v wet',
 'fine if that s the way u feel that s the way it gota b',
 'england v macedonia dont miss the goal team news txt ur national team to eg england to try wale scotland txt poboxox w wq',
 'is that seriously how you spell his name',
 'i m going to try for month ha ha only joking',
 'so pay first lar then when is da stock comin',
 'aft i finish my lunch then i go str down lor ard smth lor u finish ur lunch already',
 'ffffffffff alright no way i can meet up with you sooner',
 'just forced myself to eat a slice i m really not hungry tho this suck mark is getting worried he know i m sick when i turn down pizza lol',
 'lol your always so convincing',
 'did you catch the bus are you frying an egg did you make a tea are you eating your mom s left over dinner do you feel my love',
 'i m back amp we re packing the car now i ll let you know if there s room',
 'ahhh work i vaguely remember that what doe it feel like lol',
 'wait that s still not all that clear were you not sure about me being sarcastic or that that s why x doesn t want to live with u',
 'yeah he got in at and wa v apologetic n had fallen out and she wa actin like spoilt child and he got caught up in that till but we won t go there not doing too badly cheer you',
 'k tell me anything about you',
 'for fear of fainting with the of all that housework you just did quick have a cuppa',
 'thanks for your subscription to ringtone uk your mobile will be charged month please confirm by replying yes or no if you reply no you will not be charged',
 'yup ok i go home look at the timing then i msg again xuhui going to learn on nd may too but her lesson is at am',
 'oops i ll let you know when my roommate s done',
 'i see the letter b on my car',
 'anything lor u decide',
 'hello how s you and how did saturday go i wa just texting to see if you d decided to do anything tomo not that i m trying to invite myself or anything',
 'pls go ahead with watt i just wanted to be sure do have a great weekend abiola',
 'did i forget to tell you i want you i need you i crave you but most of all i love you my sweet arabian steed mmmmmm yummy',
 'rodger burn msg we tried to call you re your reply to our sm for a free nokia mobile free camcorder please call now for delivery tomorrow',
 'who are you seeing',
 'great i hope you like your man well endowed i am lt gt inch',
 'no call message missed call',
 'didn t you get hep b immunisation in nigeria',
 'fair enough anything going on',
 'yeah hopefully if tyler can t do it i could maybe ask around a bit',
 'u don t know how stubborn i am i didn t even want to go to the hospital i kept telling mark i m not a weak sucker hospital are for weak sucker',
 'what you thinked about me first time you saw me in class',
 'a gram usually run like lt gt a half eighth is smarter though and get you almost a whole second gram for lt gt',
 'k fyi x ha a ride early tomorrow morning but he s crashing at our place tonight',
 'wow i never realized that you were so embarassed by your accomodations i thought you liked it since i wa doing the best i could and you always seemed so happy about the cave i m sorry i didn t and don t have more to give i m sorry i offered i m sorry your room wa so embarassing',
 'sm ac sptv the new jersey devil and the detroit red wing play ice hockey correct or incorrect end reply end sptv',
 'do you know what mallika sherawat did yesterday find out now lt url gt',
 'congrats year special cinema pas for is yours call now c suprman v matrix starwars etc all free bx ip we pm dont miss out',
 'sorry i ll call later in meeting',
 'tell where you reached',
 'yes gauti and sehwag out of odi series',
 'your gonna have to pick up a burger for yourself on your way home i can t even move pain is killing me',
 'ha ha ha good joke girl are situation seeker',
 'it a part of checking iq',
 'sorry my roommate took forever it ok if i come by now',
 'ok lar i double check wif da hair dresser already he said wun cut v short he said will cut until i look nice',
 'a a valued customer i am pleased to advise you that following recent review of your mob no you are awarded with a bonus prize call',
 'today is song dedicated day which song will u dedicate for me send this to all ur valuable frnds but first rply me',
 'urgent ur awarded a complimentary trip to eurodisinc trav aco entry or to claim txt dis to morefrmmob shracomorsglsuplt l aj',
 'did you hear about the new divorce barbie it come with all of ken s stuff',
 'i plane to give on this month end',
 'wah lucky man then can save money hee',
 'finished class where are you',
 'hi babe im at home now wanna do something xx',
 'k k where are you how did you performed',
 'u can call me now',
 'i am waiting machan call me once you free',
 'thats cool i am a gentleman and will treat you with dignity and respect',
 'i like you people very much but am very shy pa',
 'doe not operate after lt gt or what',
 'it not the same here still looking for a job how much do ta s earn there',
 'sorry i ll call later',
 'k did you call me just now ah',
 'ok i am on the way to home hi hi',
 'you will be in the place of that man',
 'yup next stop',
 'i call you later don t have network if urgnt sm me',
 'for real when u getting on yo i only need more ticket and one more jacket and i m done i already used all my multis',
 'yes i started to send request to make it but pain came back so i m back in bed double coin at the factory too i gotta cash in all my nitros',
 'i m really not up to it still tonight babe',
 'ela kano il download come wen ur free',
 'yeah do don t stand to close tho you ll catch something',
 'sorry to be a pain is it ok if we meet another night i spent late afternoon in casualty and that mean i haven t done any of y stuff moro and that includes all my time sheet and that sorry',
 'smile in pleasure smile in pain smile when trouble pours like rain smile when sum hurt u smile becoz someone still love to see u smiling',
 'please call our customer service representative on between am pm a you have won a guaranteed cash or prize',
 'havent planning to buy later i check already lido only got show in e afternoon u finish work already',
 'your free ringtone is waiting to be collected simply text the password mix to to verify get usher and britney fml po box mk h ppw',
 'watching telugu movie wat abt u',
 'i see when we finish we have load of loan to pay',
 'hi wk been ok on hols now yes on for a bit of a run forgot that i have hairdresser appointment at four so need to get home n shower beforehand doe that cause prob for u',
 'i see a cup of coffee animation',
 'please don t text me anymore i have nothing else to say',
 'okay name ur price a long a it legal wen can i pick them up y u ave x am xx',
 'i m still looking for a car to buy and have not gone the driving test yet',
 'a per your request melle melle oru minnaminunginte nurungu vettam ha been set a your callertune for all caller press to copy your friend callertune',
 'wow you re right i didn t mean to do that i guess once i gave up on boston men and changed my search location to nyc something changed cuz on my signin page it still say boston',
 'umma my life and vava umma love you lot dear',
 'thanks a lot for your wish on my birthday thanks you for making my birthday truly memorable',
 'aight i ll hit you up when i get some cash',
 'how would my ip address test that considering my computer isn t a minecraft server',
 'i know grumpy old people my mom wa like you better not be lying then again i am always the one to play joke',
 'dont worry i guess he s busy',
 'what is the plural of the noun research',
 'going for dinner msg you after',
 'i m ok wif it co i like try new thing but i scared u dun like mah co u said not too loud',
 'gent we are trying to contact you last weekend draw show that you won a prize guaranteed call claim code k valid hr only ppm',
 'wa ur openin sentence very formal anyway i m fine too juz tt i m eatin too much n puttin on weight haha so anythin special happened',
 'a i entered my cabin my pa said happy b day bos i felt special she askd me lunch after lunch she invited me to her apartment we went there',
 'you are a winner u have been specially selected receive or a holiday flight inc speak to a live operator claim p min',
 'goodo yes we must speak friday egg potato ratio for tortilla needed',
 'hmm my uncle just informed me that he s paying the school directly so pls buy food',
 'private your account statement for show unredeemed bonus point to claim call identifier code expires',
 'urgent your mobile no wa awarded bonus caller prize on this is our final try to contact u call from landline box wr c ppm',
 'here is my new address apple pair all that malarky',
 'today voda number ending are selected to receive a award if you have a match please call quoting claim code standard rate app',
 'i am going to sao mu today will be done only at',
 'predict wat time ll finish buying',
 'good stuff will do',
 'just so that you know yetunde hasn t sent money yet i just sent her a text not to bother sending so it over you dont have to involve yourself in anything i shouldn t have imposed anything on you in the first place so for that i apologise',
 'are you there in room',
 'hey girl how r u hope u r well me an del r bak again long time no c give me a call sum time from lucyxx',
 'k k how much doe it cost',
 'i m home',
 'dear will call tmorrow pls accomodate',
 'first answer my question',
 'sunshine quiz wkly q win a top sony dvd player if u know which country the algarve is in txt ansr to sp tyrone',
 'want get laid tonight want real dogging location sent direct ur mob join the uk s largest dogging network bt txting gravel to nt ec a p msg p',
 'i only haf msn it s yijue hotmail com',
 'he is there you call and meet him',
 'no no i will check all room befor activity',
 'you ll not rcv any more msg from the chat svc for free hardcore service text go to if u get nothing u must age verify with yr network try again',
 'got c i lazy to type i forgot in lect i saw a pouch but like not v nice',
 'k text me when you re on the way',
 'sir waiting for your mail',
 'a swt thought nver get tired of doing little thing lovable person coz somtimes those little thing occupy d biggest part in their heart gud ni',
 'i know you are can you pls open the back',
 'yes see ya not on the dot',
 'whats the staff name who is taking class for u',
 'freemsg why haven t you replied to my text i m randy sexy female and live local luv to hear from u netcollex ltd p per msg reply stop to end',
 'ummma will call after check in our life will begin from qatar so pls pray very hard',
 'k i deleted my contact that why',
 'sindu got job in birla soft',
 'the wine is flowing and i m i have nevering',
 'yup i thk cine is better co no need go down plaza mah',
 'ok ur typical reply',
 'a per your request melle melle oru minnaminunginte nurungu vettam ha been set a your callertune for all caller press to copy your friend callertune',
 'you are everywhere dirt on the floor the window even on my shirt and sometimes when i open my mouth you are all that come flowing out i dream of my world without you then half my chore are out too a time of joy for me lot of tv show i ll see but i guess like all thing you just must exist like rain hail and mist and when my time here is done you and i become one',
 'aaooooright are you at work',
 'i m leaving my house now',
 'hello my love what are you doing did you get to that interview today are you you happy are you being a good boy do you think of me are you missing me',
 'customer service annoncement you have a new year delivery waiting for you please call now to arrange delivery',
 'you are a winner u have been specially selected receive cash or a holiday flight inc speak to a live operator claim',
 'keep yourself safe for me because i need you and i miss you already and i envy everyone that see s you in real life',
 'new car and house for my parent i have only new job in hand',
 'i m so in love with you i m excited each day i spend with you you make me so happy',
 'pls stop bootydelious f is inviting you to be her friend reply yes or no see her www sm ac u bootydelious stop send stop frnd to',
 'bangbabes ur order is on the way u should receive a service msg download ur content if u do not goto wap bangb tv on ur mobile internet service menu',
 'i place all ur point on e culture module already',
 'urgent we are trying to contact you last weekend draw show that you have won a prize guaranteed call claim code s valid hr only',
 'hi frnd which is best way to avoid missunderstding wit our beloved one s',
 'great escape i fancy the bridge but need her lager see you tomo',
 'yes it completely in out of form clark also utter waste',
 'sir i need axis bank account no and bank address',
 'hmmm thk sure got time to hop ard ya can go free abt muz call u to discus liao',
 'what time you coming down later',
 'bloody hell cant believe you forgot my surname mr ill give u a clue it spanish and begin with m',
 'well i m gonna finish my bath now have a good fine night',
 'let me know when you ve got the money so carlos can make the call',
 'u still going to the mall',
 'turn out my friend are staying for the whole show and won t be back til lt gt so feel free to go ahead and smoke that lt gt worth',
 'text her if she doesnt reply let me know so i can have her log in',
 'hi you just spoke to maneesha v we d like to know if you were satisfied with the experience reply toll free with yes or no',
 'you lifted my hope with the offer of money i am in need especially when the end of the month approach and it hurt my studying anyways have a gr weekend',
 'lol no u can trust me',
 'ok i am a gentleman and will treat you with dignity and respect',
 'he will you guy close',
 'going on nothing great bye',
 'hello handsome are you finding that job not being lazy working towards getting back that net for mummy where s my boytoy now doe he miss me',
 'haha awesome be there in a minute',
 'please call our customer service representative on freephone between am pm a you have won a guaranteed cash or prize',
 'have you got xmas radio time if not i will get it now',
 'i jus reached home i go bathe first but my si using net tell u when she finish k',
 'are you unique enough find out from th august www areyouunique co uk',
 'i m sorry i ve joined the league of people that dont keep in touch you mean a great deal to me you have been a friend at all time even at great personal cost do have a great week',
 'hi finally i completed the course',
 'it will stop on itself i however suggest she stay with someone that will be able to give or for every stool',
 'how are you doing hope you ve settled in for the new school year just wishin you a gr day',
 'gud mrng dear hav a nice day',
 'did u got that person story',
 'is your hamster dead hey so tmr i meet you at pm orchard mrt',
 'hi it kate how is your evening i hope i can see you tomorrow for a bit but i have to bloody babyjontet txt back if u can xxx',
 'found it enc lt gt where you at',
 'i sent you lt gt buck',
 'hello darlin ive finished college now so txt me when u finish if u can love kate xxx',
 'your account ha been refilled successfully by inr lt decimal gt your keralacircle prepaid account balance is r lt decimal gt your transaction id is kr lt gt',
 'goodmorning sleeping ga',
 'u call me alter at ok',
 'say until like dat i dun buy ericsson oso cannot oredi lar',
 'a i entered my cabin my pa said happy b day bos i felt special she askd me lunch after lunch she invited me to her apartment we went there',
 'aight yo dat straight dogg',
 'you please give u connection today itself before lt decimal gt or refund the bill',
 'both i shoot big load so get ready',
 'what s up bruv hope you had a great break do have a rewarding semester',
 'home so we can always chat',
 'k k good study well',
 'yup how noe leh',
 'sound great are you home now',
 'finally the match heading towards draw a your prediction',
 'tired i haven t slept well the past few night',
 'easy ah sen got selected mean it good',
 'i have to take exam with march',
 'yeah you should i think you can use your gt atm now to register not sure but if there s anyway i can help let me know but when you do be sure you are ready',
 'ok no prob take ur time',
 'there is o called ubandu which will run without installing in hard disk you can use that o to copy the important file in system and give it to repair shop',
 'sorry i ll call later',
 'u say leh of course nothing happen lar not say v romantic jus a bit only lor i thk e nite scenery not so nice leh',
 'new mobile from must go txt nokia to no collect yours today from only www tc biz optout gbp mtmsg',
 'would really appreciate if you call me just need someone to talk to',
 'will u meet ur dream partner soon is ur career off a flyng start find out free txt horo followed by ur star sign e g horo aries',
 'hey company elama po mudyadhu',
 'life is more strict than teacher bcoz teacher teach lesson amp then conduct exam but life first conduct exam amp then teach lesson happy morning',
 'dear good morning now only i am up',
 'get down in gandhipuram and walk to cross cut road right side lt gt street road and turn at first right',
 'dear we are going to our rubber place',
 'sorry battery died yeah i m here',
 'yes here tv is always available in work place',
 'text meet someone sexy today u can find a date or even flirt it up to u join just p reply with name age eg sam msg recd thirtyeight penny',
 'i have printed it oh so lt gt come upstairs',
 'or ill be a little closer like at the bus stop on the same street',
 'where are you when wil you reach here',
 'new theory argument win d situation but loses the person so dont argue with ur friend just kick them amp say i m always correct',
 'u have a secret admirer who is looking make contact with u find out who they r reveal who think ur so special call on',
 'tomarrow final hearing on my laptop case so i cant',
 'pleassssssseeeeee tel me v avent done sportsx',
 'okay no no just shining on that wa meant to be signing but that sound better',

In [118]:
from nltk import sent_tokenize
from gensim.utils import simple_preprocess

In [120]:
words=[]
for sent in corpus:
    sent_token=sent_tokenize(sent)
    for sent in sent_token:
        words.append(simple_preprocess(sent))

words[0]

['go',
 'until',
 'jurong',
 'point',
 'crazy',
 'available',
 'only',
 'in',
 'bugis',
 'great',
 'world',
 'la',
 'buffet',
 'cine',
 'there',
 'got',
 'amore',
 'wat']

In [122]:
import gensim

In [124]:
##lets train word2vec from scrach
model = gensim.models.Word2Vec(words)

In [125]:
#to get all the vocabulary
#model.wv.index_to_key

In [128]:
model.corpus_count

5569

In [130]:
model.epochs

5

In [132]:
model.wv.similar_by_word('kid')

[('ask', 0.9971358180046082),
 ('stuff', 0.9970425367355347),
 ('out', 0.9969190955162048),
 ('doe', 0.9968945980072021),
 ('haha', 0.9968720078468323),
 ('went', 0.9968569278717041),
 ('eat', 0.9968563914299011),
 ('wat', 0.9968339800834656),
 ('meet', 0.9968189597129822),
 ('oso', 0.9968119263648987)]

In [134]:
model.wv['good'].shape

(100,)

In [136]:
import numpy as np
def avg_word2vec(doc):
    # remove out-of-vocabulary words
    #sent = [word for word in doc if word in model.wv.index_to_key]
    #print(sent)
    
    return np.mean([model.wv[word] for word in doc if word in model.wv.index_to_key],axis=0)
                #or [np.zeros(len(model.wv.index_to_key))], axis=0)

In [138]:
from tqdm import tqdm

In [140]:
#apply for the entire sentences
X=[]
for i in tqdm(range(len(words))):
    X.append(avg_word2vec(words[i]))

  8%|██████                                                                       | 434/5569 [00:00<00:01, 4339.94it/s]D:\Anaconda\Lib\site-packages\numpy\core\fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
D:\Anaconda\Lib\site-packages\numpy\core\_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
100%|████████████████████████████████████████████████████████████████████████████| 5569/5569 [00:00<00:00, 5602.64it/s]

In [142]:
len(X)

5569

In [144]:
X[0]

array([-0.16808623,  0.23723473,  0.12431974,  0.08470128,  0.09756371,
       -0.4965015 ,  0.16830523,  0.4663477 , -0.2754499 , -0.11563585,
       -0.15908201, -0.34014744, -0.0416117 ,  0.11570499,  0.19181043,
       -0.15184784,  0.13904537, -0.30804235, -0.07294898, -0.5033957 ,
        0.19881624,  0.11355119,  0.0890775 , -0.22258918, -0.02495692,
       -0.01223204, -0.22252996, -0.18638292, -0.25110924,  0.03999735,
        0.2992894 ,  0.00730077,  0.08395572, -0.17518467, -0.12368042,
        0.40124896,  0.05091217, -0.1484242 , -0.11222673, -0.47285596,
        0.11056571, -0.25400066, -0.1647861 ,  0.01966916,  0.1488185 ,
        0.0176622 , -0.11715864, -0.03399112,  0.20948389,  0.1390265 ,
        0.18460068, -0.18996044, -0.08201073,  0.04706401, -0.07213174,
        0.04136057,  0.15270828,  0.03004157, -0.3642294 ,  0.18650223,
       -0.00891278,  0.13524202, -0.00275848, -0.10514083, -0.29506224,
        0.29302412,  0.08009784,  0.22744654, -0.3458754 ,  0.3962072 ,
       -0.2926608 ,  0.15557009,  0.38368717, -0.12813534,  0.33985096,
        0.06942766,  0.11121724, -0.0975244 , -0.17449787,  0.10261507,
       -0.23065932, -0.11463087, -0.26843914,  0.469738  , -0.14171527,
       -0.03317602,  0.0556267 ,  0.22668232,  0.38032416,  0.07145263,
        0.3613576 ,  0.14749174,  0.01601015,  0.04054672,  0.4169876 ,
        0.17617348,  0.14965068, -0.19757424,  0.14693171, -0.00442419],
      dtype=float32)

In [146]:
##Independent feature
##X_new=np.array(X)
X_new = np.array(X, dtype=object)

In [148]:
X_new.shape

(5569,)

In [150]:
##dependent features
y = messages[list(map(lambda x: len(x)>0 , corpus))]
y = pd.get_dummies(y['label'])
y = y.iloc[:,0].values

In [154]:
y = y.astype(int)
y

array([1, 1, 0, ..., 1, 1, 1])

In [156]:
y.shape

(5569,)

In [158]:
for i, x in enumerate(X):
    print(f"Index {i}: shape {np.array(x).shape}")

Index 0: shape (100,)
Index 1: shape (100,)
Index 2: shape (100,)
Index 3: shape (100,)
Index 4: shape (100,)
Index 5: shape (100,)
Index 6: shape (100,)
Index 7: shape (100,)
Index 8: shape (100,)
Index 9: shape (100,)
Index 10: shape (100,)
Index 11: shape (100,)
Index 12: shape (100,)
Index 13: shape (100,)
Index 14: shape (100,)
Index 15: shape (100,)
Index 16: shape (100,)
Index 17: shape (100,)
Index 18: shape (100,)
Index 19: shape (100,)
Index 20: shape (100,)
Index 21: shape (100,)
Index 22: shape (100,)
Index 23: shape (100,)
Index 24: shape (100,)
Index 25: shape (100,)
Index 26: shape (100,)
Index 27: shape (100,)
Index 28: shape (100,)
Index 29: shape (100,)
Index 30: shape (100,)
Index 31: shape (100,)
Index 32: shape (100,)
Index 33: shape (100,)
Index 34: shape (100,)
Index 35: shape (100,)
Index 36: shape (100,)
Index 37: shape (100,)
Index 38: shape (100,)
Index 39: shape (100,)
Index 40: shape (100,)
Index 41: shape (100,)
Index 42: shape (100,)
Index 43: shape (100,)
Index 44: shape (100,)
Index 45: shape (100,)
Index 46: shape (100,)
Index 47: shape (100,)
Index 48: shape (100,)
Index 49: shape (100,)
Index 50: shape (100,)
Index 51: shape (100,)
Index 52: shape (100,)
Index 53: shape (100,)
Index 54: shape (100,)
Index 55: shape (100,)
Index 56: shape (100,)
Index 57: shape (100,)
Index 58: shape (100,)
Index 59: shape (100,)
Index 60: shape (100,)
Index 61: shape (100,)
Index 62: shape (100,)
Index 63: shape (100,)
Index 64: shape (100,)
Index 65: shape (100,)
Index 66: shape (100,)
Index 67: shape (100,)
Index 68: shape (100,)
Index 69: shape (100,)
Index 70: shape (100,)
Index 71: shape (100,)
Index 72: shape (100,)
Index 73: shape (100,)
Index 74: shape (100,)
Index 75: shape (100,)
Index 76: shape (100,)
Index 77: shape (100,)
Index 78: shape (100,)
Index 79: shape (100,)
Index 80: shape (100,)
Index 81: shape (100,)
Index 82: shape (100,)
Index 83: shape (100,)
Index 84: shape (100,)
Index 85: shape (100,)
Index 86: shape (100,)
Index 87: shape (100,)
Index 88: shape (100,)
Index 89: shape (100,)
Index 90: shape (100,)
Index 91: shape (100,)
Index 92: shape (100,)
Index 93: shape (100,)
Index 94: shape (100,)
Index 95: shape (100,)
Index 96: shape (100,)
Index 97: shape (100,)
Index 98: shape (100,)
Index 99: shape (100,)
Index 100: shape (100,)
Index 101: shape (100,)
Index 102: shape (100,)
Index 103: shape (100,)
Index 104: shape (100,)
Index 105: shape (100,)
Index 106: shape (100,)
Index 107: shape (100,)
Index 108: shape (100,)
Index 109: shape (100,)
Index 110: shape (100,)
Index 111: shape (100,)
Index 112: shape (100,)
Index 113: shape (100,)
Index 114: shape (100,)
Index 115: shape (100,)
Index 116: shape (100,)
Index 117: shape (100,)
Index 118: shape (100,)
Index 119: shape (100,)
Index 120: shape (100,)
Index 121: shape (100,)
Index 122: shape (100,)
Index 123: shape (100,)
Index 124: shape (100,)
Index 125: shape (100,)
Index 126: shape (100,)
Index 127: shape (100,)
Index 128: shape (100,)
Index 129: shape (100,)
Index 130: shape (100,)
Index 131: shape (100,)
Index 132: shape (100,)
Index 133: shape (100,)
Index 134: shape (100,)
Index 135: shape (100,)
Index 136: shape (100,)
Index 137: shape (100,)
Index 138: shape (100,)
Index 139: shape (100,)
Index 140: shape (100,)
Index 141: shape (100,)
Index 142: shape (100,)
Index 143: shape (100,)
Index 144: shape (100,)
Index 145: shape (100,)
Index 146: shape (100,)
Index 147: shape (100,)
Index 148: shape (100,)
Index 149: shape (100,)
Index 150: shape (100,)
Index 151: shape (100,)
Index 152: shape (100,)
Index 153: shape (100,)
Index 154: shape (100,)
Index 155: shape (100,)
Index 156: shape (100,)
Index 157: shape (100,)
Index 158: shape (100,)
Index 159: shape (100,)
Index 160: shape (100,)
Index 161: shape (100,)
Index 162: shape (100,)
Index 163: shape (100,)
Index 164: shape (100,)
Index 165: shape (100,)
Index 166: shape (100,)
Index 167: shape (100,)
Index 168: shape (100,)
Index 169: shape (100,)
Index 170: shape (100,)
Index 171: shape (100,)
Index 172: shape (100,)
Index 173: shape (100,)
Index 174: shape (100,)
Index 175: shape (100,)
Index 176: shape (100,)
Index 177: shape (100,)
Index 178: shape (100,)
Index 179: shape (100,)
Index 180: shape (100,)
Index 181: shape (100,)
Index 182: shape (100,)
Index 183: shape (100,)
Index 184: shape (100,)
Index 185: shape (100,)
Index 186: shape (100,)
Index 187: shape (100,)
Index 188: shape (100,)
Index 189: shape (100,)
Index 190: shape (100,)
Index 191: shape (100,)
Index 192: shape (100,)
Index 193: shape (100,)
Index 194: shape (100,)
Index 195: shape (100,)
Index 196: shape (100,)
Index 197: shape (100,)
Index 198: shape (100,)
Index 199: shape (100,)
Index 200: shape (100,)
Index 201: shape (100,)
Index 202: shape (100,)
Index 203: shape (100,)
Index 204: shape (100,)
Index 205: shape (100,)
Index 206: shape (100,)
Index 207: shape (100,)
Index 208: shape (100,)
Index 209: shape (100,)
Index 210: shape (100,)
Index 211: shape (100,)
Index 212: shape (100,)
Index 213: shape (100,)
Index 214: shape (100,)
Index 215: shape (100,)
Index 216: shape (100,)
Index 217: shape (100,)
Index 218: shape (100,)
Index 219: shape (100,)
Index 220: shape (100,)
Index 221: shape (100,)
Index 222: shape (100,)
Index 223: shape (100,)
Index 224: shape (100,)
Index 225: shape (100,)
Index 226: shape (100,)
Index 227: shape (100,)
Index 228: shape (100,)
Index 229: shape (100,)
Index 230: shape (100,)
Index 231: shape (100,)
Index 232: shape (100,)
Index 233: shape (100,)
Index 234: shape (100,)
Index 235: shape (100,)
Index 236: shape (100,)
Index 237: shape (100,)
Index 238: shape (100,)
Index 239: shape (100,)
Index 240: shape (100,)
Index 241: shape (100,)
Index 242: shape (100,)
Index 243: shape (100,)
Index 244: shape (100,)
Index 245: shape (100,)
Index 246: shape (100,)
Index 247: shape (100,)
Index 248: shape (100,)
Index 249: shape (100,)
Index 250: shape (100,)
Index 251: shape (100,)
Index 252: shape (100,)
Index 253: shape (100,)
Index 254: shape (100,)
Index 255: shape (100,)
Index 256: shape (100,)
Index 257: shape (100,)
Index 258: shape (100,)
Index 259: shape (100,)
Index 260: shape (100,)
Index 261: shape (100,)
Index 262: shape (100,)
Index 263: shape (100,)
Index 264: shape (100,)
Index 265: shape (100,)
Index 266: shape (100,)
Index 267: shape (100,)
Index 268: shape (100,)
Index 269: shape (100,)
Index 270: shape (100,)
Index 271: shape (100,)
Index 272: shape (100,)
Index 273: shape (100,)
Index 274: shape (100,)
Index 275: shape (100,)
Index 276: shape (100,)
Index 277: shape (100,)
Index 278: shape (100,)
Index 279: shape (100,)
Index 280: shape (100,)
Index 281: shape (100,)
Index 282: shape (100,)
Index 283: shape (100,)
Index 284: shape (100,)
Index 285: shape (100,)
Index 286: shape (100,)
Index 287: shape (100,)
Index 288: shape (100,)
Index 289: shape (100,)
Index 290: shape (100,)
Index 291: shape (100,)
Index 292: shape (100,)
Index 293: shape (100,)
Index 294: shape (100,)
Index 295: shape (100,)
Index 296: shape (100,)
Index 297: shape (100,)
Index 298: shape (100,)
Index 299: shape (100,)
Index 300: shape (100,)
Index 301: shape (100,)
Index 302: shape (100,)
Index 303: shape (100,)
Index 304: shape (100,)
Index 305: shape (100,)
Index 306: shape (100,)
Index 307: shape (100,)
Index 308: shape (100,)
Index 309: shape (100,)
Index 310: shape (100,)
Index 311: shape (100,)
Index 312: shape (100,)
Index 313: shape (100,)
Index 314: shape (100,)
Index 315: shape (100,)
Index 316: shape (100,)
Index 317: shape (100,)
Index 318: shape (100,)
Index 319: shape (100,)
Index 320: shape (100,)
Index 321: shape (100,)
Index 322: shape (100,)
Index 323: shape (100,)
Index 324: shape (100,)
Index 325: shape (100,)
Index 326: shape (100,)
Index 327: shape (100,)
Index 328: shape (100,)
Index 329: shape (100,)
Index 330: shape (100,)
Index 331: shape (100,)
Index 332: shape (100,)
Index 333: shape (100,)
Index 334: shape (100,)
Index 335: shape (100,)
Index 336: shape (100,)
Index 337: shape (100,)
Index 338: shape (100,)
Index 339: shape (100,)
Index 340: shape (100,)
Index 341: shape (100,)
Index 342: shape (100,)
Index 343: shape (100,)
Index 344: shape (100,)
Index 345: shape (100,)
Index 346: shape (100,)
Index 347: shape (100,)
Index 348: shape (100,)
Index 349: shape (100,)
Index 350: shape (100,)
Index 351: shape (100,)
Index 352: shape (100,)
Index 353: shape (100,)
Index 354: shape (100,)
Index 355: shape (100,)
Index 356: shape (100,)
Index 357: shape (100,)
Index 358: shape (100,)
Index 359: shape (100,)
Index 360: shape (100,)
Index 361: shape (100,)
Index 362: shape (100,)
Index 363: shape (100,)
Index 364: shape (100,)
Index 365: shape (100,)
Index 366: shape (100,)
Index 367: shape (100,)
Index 368: shape (100,)
Index 369: shape (100,)
Index 370: shape (100,)
Index 371: shape (100,)
Index 372: shape (100,)
Index 373: shape (100,)
Index 374: shape (100,)
Index 375: shape (100,)
Index 376: shape (100,)
Index 377: shape (100,)
Index 378: shape (100,)
Index 379: shape (100,)
Index 380: shape (100,)
Index 381: shape (100,)
Index 382: shape (100,)
Index 383: shape (100,)
Index 384: shape (100,)
Index 385: shape (100,)
Index 386: shape (100,)
Index 387: shape (100,)
Index 388: shape (100,)
Index 389: shape (100,)
Index 390: shape (100,)
Index 391: shape (100,)
Index 392: shape (100,)
Index 393: shape (100,)
Index 394: shape (100,)
Index 395: shape (100,)
Index 396: shape (100,)
Index 397: shape (100,)
Index 398: shape (100,)
Index 399: shape (100,)
Index 400: shape (100,)
Index 401: shape (100,)
Index 402: shape (100,)
Index 403: shape (100,)
Index 404: shape (100,)
Index 405: shape (100,)
Index 406: shape (100,)
Index 407: shape (100,)
Index 408: shape (100,)
Index 409: shape (100,)
Index 410: shape (100,)
Index 411: shape (100,)
Index 412: shape (100,)
Index 413: shape (100,)
Index 414: shape (100,)
Index 415: shape (100,)
Index 416: shape (100,)
Index 417: shape (100,)
Index 418: shape (100,)
Index 419: shape (100,)
Index 420: shape (100,)
Index 421: shape (100,)
Index 422: shape (100,)
Index 423: shape (100,)
Index 424: shape (100,)
Index 425: shape (100,)
Index 426: shape (100,)
Index 427: shape (100,)
Index 428: shape (100,)
Index 429: shape (100,)
Index 430: shape (100,)
Index 431: shape (100,)
Index 432: shape (100,)
Index 433: shape (100,)
Index 434: shape (100,)
Index 435: shape (100,)
Index 436: shape (100,)
Index 437: shape (100,)
Index 438: shape (100,)
Index 439: shape (100,)
Index 440: shape (100,)
Index 441: shape (100,)
Index 442: shape (100,)
Index 443: shape (100,)
Index 444: shape (100,)
Index 445: shape (100,)
Index 446: shape (100,)
Index 447: shape (100,)
Index 448: shape (100,)
Index 449: shape (100,)
Index 450: shape (100,)
Index 451: shape ()
Index 452: shape (100,)
Index 453: shape (100,)
Index 454: shape (100,)
Index 455: shape (100,)
Index 456: shape (100,)
Index 457: shape (100,)
Index 458: shape (100,)
Index 459: shape (100,)
Index 460: shape (100,)
Index 461: shape (100,)
Index 462: shape (100,)
Index 463: shape (100,)
Index 464: shape (100,)
Index 465: shape (100,)
Index 466: shape (100,)
Index 467: shape (100,)
Index 468: shape (100,)
Index 469: shape (100,)
Index 470: shape (100,)
Index 471: shape (100,)
Index 472: shape (100,)
Index 473: shape (100,)
Index 474: shape (100,)
Index 475: shape (100,)
Index 476: shape (100,)
Index 477: shape (100,)
Index 478: shape (100,)
Index 479: shape (100,)
Index 480: shape (100,)
Index 481: shape (100,)
Index 482: shape (100,)
Index 483: shape (100,)
Index 484: shape (100,)
Index 485: shape (100,)
Index 486: shape (100,)
Index 487: shape (100,)
Index 488: shape (100,)
Index 489: shape (100,)
Index 490: shape (100,)
Index 491: shape (100,)
Index 492: shape (100,)
Index 493: shape (100,)
Index 494: shape (100,)
Index 495: shape (100,)
Index 496: shape (100,)
Index 497: shape (100,)
Index 498: shape (100,)
Index 499: shape (100,)
Index 500: shape (100,)
Index 501: shape (100,)
Index 502: shape (100,)
Index 503: shape (100,)
Index 504: shape (100,)
Index 505: shape (100,)
Index 506: shape (100,)
Index 507: shape (100,)
Index 508: shape (100,)
Index 509: shape (100,)
Index 510: shape (100,)
Index 511: shape (100,)
Index 512: shape (100,)
Index 513: shape (100,)
Index 514: shape (100,)
Index 515: shape (100,)
Index 516: shape (100,)
Index 517: shape (100,)
Index 518: shape (100,)
Index 519: shape (100,)
Index 520: shape (100,)
Index 521: shape (100,)
Index 522: shape (100,)
Index 523: shape (100,)
Index 524: shape (100,)
Index 525: shape (100,)
Index 526: shape (100,)
Index 527: shape (100,)
Index 528: shape (100,)
Index 529: shape (100,)
Index 530: shape (100,)
Index 531: shape (100,)
Index 532: shape (100,)
Index 533: shape (100,)
Index 534: shape (100,)
Index 535: shape (100,)
Index 536: shape (100,)
Index 537: shape (100,)
Index 538: shape (100,)
Index 539: shape (100,)
Index 540: shape (100,)
Index 541: shape (100,)
Index 542: shape (100,)
Index 543: shape (100,)
Index 544: shape (100,)
Index 545: shape (100,)
Index 546: shape (100,)
Index 547: shape (100,)
Index 548: shape (100,)
Index 549: shape (100,)
Index 550: shape (100,)
Index 551: shape (100,)
Index 552: shape (100,)
Index 553: shape (100,)
Index 554: shape (100,)
Index 555: shape (100,)
Index 556: shape (100,)
Index 557: shape (100,)
Index 558: shape (100,)
Index 559: shape (100,)
Index 560: shape (100,)
Index 561: shape (100,)
Index 562: shape (100,)
Index 563: shape (100,)
Index 564: shape (100,)
Index 565: shape (100,)
Index 566: shape (100,)
Index 567: shape (100,)
Index 568: shape (100,)
Index 569: shape (100,)
Index 570: shape (100,)
Index 571: shape (100,)
Index 572: shape (100,)
Index 573: shape (100,)
Index 574: shape (100,)
Index 575: shape (100,)
Index 576: shape (100,)
Index 577: shape (100,)
Index 578: shape (100,)
Index 579: shape (100,)
Index 580: shape (100,)
Index 581: shape (100,)
Index 582: shape (100,)
Index 583: shape (100,)
Index 584: shape (100,)
Index 585: shape (100,)
Index 586: shape (100,)
Index 587: shape (100,)
Index 588: shape (100,)
Index 589: shape (100,)
Index 590: shape (100,)
Index 591: shape (100,)
Index 592: shape (100,)
Index 593: shape (100,)
Index 594: shape (100,)
Index 595: shape (100,)
Index 596: shape (100,)
Index 597: shape (100,)
Index 598: shape (100,)
Index 599: shape (100,)
Index 600: shape (100,)
Index 601: shape (100,)
Index 602: shape (100,)
Index 603: shape (100,)
Index 604: shape (100,)
Index 605: shape (100,)
Index 606: shape (100,)
Index 607: shape (100,)
Index 608: shape (100,)
Index 609: shape (100,)
Index 610: shape (100,)
Index 611: shape (100,)
Index 612: shape (100,)
Index 613: shape (100,)
Index 614: shape (100,)
Index 615: shape (100,)
Index 616: shape (100,)
Index 617: shape (100,)
Index 618: shape (100,)
Index 619: shape (100,)
Index 620: shape (100,)
Index 621: shape (100,)
Index 622: shape (100,)
Index 623: shape (100,)
Index 624: shape (100,)
Index 625: shape (100,)
Index 626: shape (100,)
Index 627: shape (100,)
Index 628: shape (100,)
Index 629: shape (100,)
Index 630: shape (100,)
Index 631: shape (100,)
Index 632: shape (100,)
Index 633: shape (100,)
Index 634: shape (100,)
Index 635: shape (100,)
Index 636: shape (100,)
Index 637: shape (100,)
Index 638: shape (100,)
Index 639: shape (100,)
Index 640: shape (100,)
Index 641: shape (100,)
Index 642: shape (100,)
Index 643: shape (100,)
Index 644: shape (100,)
Index 645: shape (100,)
Index 646: shape (100,)
Index 647: shape (100,)
Index 648: shape (100,)
Index 649: shape (100,)
Index 650: shape (100,)
Index 651: shape (100,)
Index 652: shape (100,)
Index 653: shape (100,)
Index 654: shape (100,)
Index 655: shape (100,)
Index 656: shape (100,)
Index 657: shape (100,)
Index 658: shape (100,)
Index 659: shape (100,)
Index 660: shape (100,)
Index 661: shape (100,)
Index 662: shape (100,)
Index 663: shape (100,)
Index 664: shape (100,)
Index 665: shape (100,)
Index 666: shape (100,)
Index 667: shape (100,)
Index 668: shape (100,)
Index 669: shape (100,)
Index 670: shape (100,)
Index 671: shape (100,)
Index 672: shape (100,)
Index 673: shape (100,)
Index 674: shape (100,)
Index 675: shape (100,)
Index 676: shape (100,)
Index 677: shape (100,)
Index 678: shape (100,)
Index 679: shape (100,)
Index 680: shape (100,)
Index 681: shape (100,)
Index 682: shape (100,)
Index 683: shape (100,)
Index 684: shape (100,)
Index 685: shape (100,)
Index 686: shape (100,)
Index 687: shape (100,)
Index 688: shape (100,)
Index 689: shape (100,)
Index 690: shape (100,)
Index 691: shape (100,)
Index 692: shape (100,)
Index 693: shape (100,)
Index 694: shape (100,)
Index 695: shape (100,)
Index 696: shape (100,)
Index 697: shape (100,)
Index 698: shape (100,)
Index 699: shape (100,)
Index 700: shape (100,)
Index 701: shape (100,)
Index 702: shape (100,)
Index 703: shape (100,)
Index 704: shape (100,)
Index 705: shape (100,)
Index 706: shape (100,)
Index 707: shape (100,)
Index 708: shape (100,)
Index 709: shape (100,)
Index 710: shape (100,)
Index 711: shape (100,)
Index 712: shape (100,)
Index 713: shape (100,)
Index 714: shape (100,)
Index 715: shape (100,)
Index 716: shape (100,)
Index 717: shape (100,)
Index 718: shape (100,)
Index 719: shape (100,)
Index 720: shape (100,)
Index 721: shape (100,)
Index 722: shape (100,)
Index 723: shape (100,)
Index 724: shape (100,)
Index 725: shape (100,)
Index 726: shape (100,)
Index 727: shape (100,)
Index 728: shape (100,)
Index 729: shape (100,)
Index 730: shape (100,)
Index 731: shape (100,)
Index 732: shape (100,)
Index 733: shape (100,)
Index 734: shape (100,)
Index 735: shape (100,)
Index 736: shape (100,)
Index 737: shape (100,)
Index 738: shape (100,)
Index 739: shape (100,)
Index 740: shape (100,)
Index 741: shape (100,)
Index 742: shape (100,)
Index 743: shape (100,)
Index 744: shape (100,)
Index 745: shape (100,)
Index 746: shape (100,)
Index 747: shape (100,)
Index 748: shape (100,)
Index 749: shape (100,)
Index 750: shape (100,)
Index 751: shape (100,)
Index 752: shape (100,)
Index 753: shape (100,)
Index 754: shape (100,)
Index 755: shape (100,)
Index 756: shape (100,)
Index 757: shape (100,)
Index 758: shape (100,)
Index 759: shape (100,)
Index 760: shape (100,)
Index 761: shape (100,)
Index 762: shape (100,)
Index 763: shape (100,)
Index 764: shape (100,)
Index 765: shape (100,)
Index 766: shape (100,)
Index 767: shape (100,)
Index 768: shape (100,)
Index 769: shape (100,)
Index 770: shape (100,)
Index 771: shape (100,)
Index 772: shape (100,)
Index 773: shape (100,)
Index 774: shape (100,)
Index 775: shape (100,)
Index 776: shape (100,)
Index 777: shape (100,)
Index 778: shape (100,)
Index 779: shape (100,)
Index 780: shape (100,)
Index 781: shape (100,)
Index 782: shape (100,)
Index 783: shape ()
Index 784: shape (100,)
Index 785: shape (100,)
Index 786: shape (100,)
Index 787: shape (100,)
Index 788: shape (100,)
Index 789: shape (100,)
Index 790: shape (100,)
Index 791: shape (100,)
Index 792: shape (100,)
Index 793: shape (100,)
Index 794: shape (100,)
Index 795: shape (100,)
Index 796: shape (100,)
Index 797: shape (100,)
Index 798: shape (100,)
Index 799: shape (100,)
Index 800: shape (100,)
Index 801: shape (100,)
Index 802: shape (100,)
Index 803: shape (100,)
Index 804: shape (100,)
Index 805: shape (100,)
Index 806: shape (100,)
Index 807: shape (100,)
Index 808: shape (100,)
Index 809: shape (100,)
Index 810: shape (100,)
Index 811: shape (100,)
Index 812: shape (100,)
Index 813: shape (100,)
Index 814: shape (100,)
Index 815: shape (100,)
Index 816: shape (100,)
Index 817: shape (100,)
Index 818: shape (100,)
Index 819: shape (100,)
Index 820: shape (100,)
Index 821: shape (100,)
Index 822: shape (100,)
Index 823: shape (100,)
Index 824: shape (100,)
Index 825: shape (100,)
Index 826: shape (100,)
Index 827: shape (100,)
Index 828: shape (100,)
Index 829: shape (100,)
Index 830: shape (100,)
Index 831: shape (100,)
Index 832: shape (100,)
Index 833: shape (100,)
Index 834: shape (100,)
Index 835: shape (100,)
Index 836: shape (100,)
Index 837: shape (100,)

In [160]:
## this is the final independent features
# df=pd.DataFrame()
# for i in range(0,len(X)):
#     df=df.append(pd.DataFrame(X[i].reshape(1,-1)),ignore_index=True)

# rows = [x.reshape(1, -1) for x in X]
# df = pd.DataFrame(np.vstack(rows))

# X_clean = [x for x in X if np.array(x).shape == (100,)]
# df = pd.DataFrame(np.vstack(X_clean))

In [162]:
fixed_length = 100
X_fixed = []

for i, x in enumerate(X):
    x = np.array(x).flatten()
    if len(x) < fixed_length:
        # Pad with zeros at the end
        x = np.pad(x, (0, fixed_length - len(x)), mode='constant')
    elif len(x) > fixed_length:
        # Trim extra values
        x = x[:fixed_length]
    X_fixed.append(x)

In [164]:
rows = [x.reshape(1, -1) for x in X_fixed]
df = pd.DataFrame(np.vstack(rows))

In [166]:
df.shape

(5569, 100)

In [168]:
df.head()

,0,1,2,3,4,5,6,7,8,9,...,90,91,92,93,94,95,96,97,98,99
0,-0.168086,0.237235,0.124320,0.084701,0.097564,-0.496502,0.168305,0.466348,-0.275450,-0.115636,...,0.361358,0.147492,0.016010,0.040547,0.416988,0.176173,0.149651,-0.197574,0.146932,-0.004424
1,-0.157158,0.212889,0.107652,0.073962,0.088060,-0.438548,0.138958,0.416169,-0.241294,-0.097067,...,0.323181,0.123781,0.009252,0.030100,0.358278,0.149132,0.132442,-0.181256,0.133731,-0.010982
2,-0.182129,0.255057,0.134364,0.098207,0.092645,-0.534734,0.167066,0.464374,-0.291990,-0.145462,...,0.354069,0.145737,0.009087,0.019074,0.430688,0.174047,0.097025,-0.232790,0.170839,0.015398
3,-0.234938,0.321891,0.162226,0.119405,0.128587,-0.676902,0.222630,0.640392,-0.377494,-0.148909,...,0.495875,0.197133,0.017867,0.062225,0.553872,0.238906,0.219897,-0.270563,0.199128,-0.015783
4,-0.209019,0.269090,0.143865,0.099015,0.117574,-0.578024,0.188027,0.552503,-0.327517,-0.133294,...,0.429215,0.169729,0.020814,0.055470,0.477486,0.211305,0.183209,-0.244473,0.167241,-0.013581

In [170]:
##Independent feature
X = df

In [172]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [174]:
X_train.head()

,0,1,2,3,4,5,6,7,8,9,...,90,91,92,93,94,95,96,97,98,99
2604,-0.227067,0.309265,0.164038,0.112151,0.126525,-0.649563,0.209865,0.608652,-0.364781,-0.158510,...,0.473501,0.188024,0.017868,0.049325,0.531986,0.227108,0.181289,-0.266798,0.186694,-0.007447
99,-0.161890,0.211842,0.115322,0.064273,0.095227,-0.456271,0.145730,0.427832,-0.247998,-0.111557,...,0.332782,0.132096,0.016501,0.036376,0.381714,0.169843,0.140439,-0.185549,0.141377,-0.007245
4309,-0.208532,0.292006,0.156011,0.106905,0.115860,-0.608542,0.197921,0.563156,-0.338962,-0.150031,...,0.440525,0.178377,0.018981,0.042833,0.504222,0.212712,0.153878,-0.253578,0.180295,0.000443
2005,-0.210726,0.266733,0.138659,0.091778,0.118159,-0.572883,0.191214,0.555779,-0.322358,-0.133267,...,0.436540,0.173245,0.022655,0.055657,0.478494,0.219638,0.196152,-0.234848,0.155758,-0.016641
1838,-0.188101,0.277192,0.150039,0.102703,0.104659,-0.572987,0.185624,0.510399,-0.315945,-0.148515,...,0.395289,0.160715,0.012008,0.025744,0.466648,0.186289,0.125955,-0.237284,0.177478,0.007984

In [176]:
y_train

array([1, 1, 0, ..., 1, 1, 1])

In [178]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier()

In [180]:
classifier.fit(X_train, y_train)

RandomForestClassifier()

In [182]:
y_pred = classifier.predict(X_test)
y_pred

array([1, 1, 0, ..., 1, 1, 1])

In [186]:
from sklearn.metrics import accuracy_score, classification_report
print("accuracy =>", accuracy_score(y_test, y_pred) * 100 , "%")
print('classification report :\n ', classification_report(y_test, y_pred))

accuracy => 97.48653500897666 %
classification report :
                precision    recall  f1-score   support

           0       0.89      0.90      0.90       133
           1       0.99      0.98      0.99       981

    accuracy                           0.97      1114
   macro avg       0.94      0.94      0.94      1114
weighted avg       0.98      0.97      0.97      1114